### ISSUE TITLE
why require windows users to use wsl?

### ISSUE THREAD

**Issue by cktang88** [VandyHacks/vh-dev-training#1]
windows works just fine for web dev??

**Comment by cktang88** [comment]
also https://github.com/bmatzelle/gow + 
https://github.com/mridgers/clink
allows lots of linux-like commands

**Comment by bencooper222** [comment]
Not really required but it's the best supported solution. At this point, it's more important that we make consistent and somewhat rational decisions than that we allow for individual tech decisions.
